name: Docker Image CI

on:
  push:
    branches: [  JoshOps-pirum-tech-demo ]
  pull_request:
    branches: [  JoshOps-pirum-tech-demo ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./pirum-tech-demo --file ./pirum-tech-demo/Dockerfile --tag my-image-name:$(date +%s)

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: test-ecr
      run: |
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:my-image-name:$(date +%s)