name: Docker Image CI

on:
  push:
    branches: [  JoshOps-pirum-tech-demo ]
  pull_request:
    branches: [  JoshOps-pirum-tech-demo ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./pirum-tech-demo --file Dockerfile --tag my-image-name:$(date +%s)